### ISSUE TITLE
Can't start the project

### ISSUE THREAD

**Issue by nikitatrifan** [yankouskia/Shop#17]
`> Shop@0.0.6 add-db /Users/${user}/Documents/Projects/_shop/www
`> node ./init_db.js
`
`
`/Users/${user}/Documents/Projects/_shop/www/node_modules/mongodb/lib/server.js:242
`        process.nextTick(function() { throw err; })
`                                      ^
`Error: connect ECONNREFUSED 127.0.0.1:27017
`    at Object.exports._errnoException (util.js:1026:11)
`    at exports._exceptionWithHostPort (util.js:1049:20)
`    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
`
`npm ERR! Darwin 16.1.0
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "add-db"
`npm ERR! node v6.9.1
`npm ERR! npm  v3.10.8
`npm ERR! code ELIFECYCLE
`npm ERR! Shop@0.0.6 add-db: `node ./init_db.js`
`npm ERR! Exit status 1
`npm ERR! 
`npm ERR! Failed at the Shop@0.0.6 add-db script 'node ./init_db.js'.
`npm ERR! Make sure you have the latest version of node.js and npm installed.
`npm ERR! If you do, this is most likely a problem with the Shop package,
`npm ERR! not with npm itself.
`npm ERR! Tell the author that this fails on your system:
`npm ERR!     node ./init_db.js
`npm ERR! You can get information on how to open an issue for this project with:
`npm ERR!     npm bugs Shop
`npm ERR! Or if that isn't available, you can get their info via:
`npm ERR!     npm owner ls Shop
`npm ERR! There is likely additional logging output above.
`
`npm ERR! Please include the following file with any support request:
`npm ERR!     /Users/${user}/Documents/Projects/_shop/www/npm-debug.log

Maybe the reason is 6.9.1 version of node?

**Comment by yankouskia** [comment]
@expdevelop Hello, I have updated `package.json` dependencies for using latest LTS version of Node. 
This problem is likely on your side, please, try to check your mongo connection.
Do you have MongoDB installed and running?
