### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by eeeman1** [yankouskia/Shop#18]
error connection
(node:5539) Warning: a promise was rejected with a non-error: [object Undefined]
(node:5539) Warning: a promise was rejected with a non-error: [object Undefined]
undefined

**Comment by yankouskia** [comment]
@eeeman1 could you provide a little bit more info?
Node version, npm version, call stack?

**Comment by eeeman1** [comment]
node - v8.4.0
npm - 5.3.0
npm start

**Comment by yankouskia** [comment]
@eeeman1 have you installed mongo?

**Comment by eeeman1** [comment]
mongo not installed
